// src/shared/config/launcher.ts
// 在 PATH 里安装一个 launcher shim，让用户配的别名（如 bb）调用转发到 jc。
//
// 设计动机：
// 当前 router 看到的是 argv slice，shell 在 Node 启动前就要找到 executable。
// 单纯改源码不可能让 `bb mgr list` 跑通——必须在 PATH 中实际放一个 launcher。
//
// 实现要点：
// 1. 纯函数化：不直接 `which jc`、不直接写盘。所有副作用通过参数传入的目录执行。
//    这样测试可以用临时 bin 目录隔离，不动测试机真实 PATH。
// 2. ownership marker：每个 launcher 文件首行写 `# jc-managed-launcher: <name>`。
//    reset 时只删带 marker 的；非 jc 管理的同名文件绝不动。
// 3. 跨平台：POSIX 用 symlink；Windows 用 .cmd + 无扩展名 shim（给 Git Bash 用）。
// 4. 不复制 dist 内容：launcher 体积小（< 200 字节），独立于 node_modules 状态。
import { existsSync, readFileSync, writeFileSync, symlinkSync, unlinkSync, openSync, readSync, closeSync } from 'fs'
import { spawnSync } from 'child_process'
import { join } from 'path'
import { META } from '../meta.js'

export const LAUNCHER_MARKER = '# jc-managed-launcher:'

// launcher 文件内容：marker 在首行用于识别所有权。
// POSIX 版本直接 `exec jc "$@"`；Windows .cmd 用 `@echo off` + `jc %*`。
function posixContent(name: string): string {
  return [
    LAUNCHER_MARKER + ' ' + name,
    '# Generated by jc mgr cname. Do not edit.',
    'exec jc "$@"',
    '',
  ].join('\n')
}

function windowsCmdContent(name: string): string {
  return [
    '@echo off',
    'REM ' + LAUNCHER_MARKER + ' ' + name,
    'REM Generated by jc mgr cname. Do not edit.',
    'jc %*',
    '',
  ].join('\r\n')
}

// 无扩展名 shim：Git Bash / WSL 在 Windows 上需要不带 .cmd 的可执行名。
// 通过 spawn `cmd //c "<name>.cmd ..."` 实现，避免解析 `%*` 的兼容问题。
function windowsBashShimContent(name: string): string {
  return [
    '#!/usr/bin/env bash',
    LAUNCHER_MARKER + ' ' + name,
    '# Generated by jc mgr cname. Do not edit.',
    `exec cmd //c "${name}.cmd" "$@"`,
    '',
  ].join('\n')
}

// 解析目标文件清单（不实际写盘）。
// platform: 'posix' | 'win32'。当 'posix' 时只生成一个无扩展名 symlink/shim；
// 当 'win32' 时生成 .cmd + bash shim。
export interface PlanEntry {
  file: string
  kind: 'symlink' | 'cmd' | 'bash-shim'
  content?: string  // symlink 时为 target；其他为写入文本
}

export function planLauncherFiles(args: {
  binDir: string
  name: string
  jcPath: string  // symlink 目标；Windows .cmd 不直接用，但保留供将来 .cmd 调绝对路径时使用
  platform: 'posix' | 'win32'
}): PlanEntry[] {
  const { binDir, name, jcPath, platform } = args
  if (platform === 'posix') {
    return [{ file: join(binDir, name), kind: 'symlink', content: jcPath }]
  }
  // Windows
  return [
    { file: join(binDir, name + '.cmd'), kind: 'cmd', content: windowsCmdContent(name) },
    { file: join(binDir, name), kind: 'bash-shim', content: windowsBashShimContent(name) },
  ]
}

// 实际写盘。返回已写入的文件清单（用于 rollback 或登记到 config）。
export function installLauncher(args: {
  binDir: string
  name: string
  jcPath: string
  platform: 'posix' | 'win32'
}): { installed: string[]; failed?: string } {
  const plan = planLauncherFiles(args)
  const installed: string[] = []
  try {
    for (const p of plan) {
      if (p.kind === 'symlink') {
        // symlink 永远允许覆盖：所有权由调用方传入的 name 标识，不依赖目标文件内容
        try { unlinkSync(p.file) } catch { /* 文件不存在 OK */ }
        symlinkSync(p.content!, p.file, 'file')
      } else {
        if (existsSync(p.file) && !isOwned(p.file)) {
          throw new Error(`文件已存在且非 jc 管理: ${p.file}`)
        }
        writeFileSync(p.file, p.content!, 'utf-8')
      }
      installed.push(p.file)
    }
    return { installed }
  } catch (e) {
    // rollback: 删除已安装的文件
    for (const f of installed) {
      try { unlinkSync(f) } catch { /* ignore */ }
    }
    return { installed: [], failed: (e as Error).message }
  }
}

// 删除 launcher 文件。只删带 ownership marker 的；绝不删 jc 自身。
export function uninstallLauncher(files: string[]): { removed: string[]; kept: string[]; failed?: string } {
  const removed: string[] = []
  const kept: string[] = []
  for (const f of files) {
    if (!existsSync(f)) continue
    if (!isOwned(f)) {
      kept.push(f)
      continue
    }
    try {
      unlinkSync(f)
      removed.push(f)
    } catch (e) {
      return { removed, kept, failed: `${f}: ${(e as Error).message}` }
    }
  }
  return { removed, kept }
}

// 检查文件是否 jc 管理（首行含 marker）。
// 只读前 200 字节，避免读大文件。
export function isOwned(file: string): boolean {
  try {
    const fd = openSync(file, 'r')
    try {
      const buf = Buffer.alloc(200)
      const n = readSync(fd, buf, 0, 200, 0)
      const head = buf.slice(0, n).toString('utf-8')
      return head.includes(LAUNCHER_MARKER)
    } finally {
      closeSync(fd)
    }
  } catch {
    return false
  }
}

// 查找当前 binary 的 bin 目录（通过 PATH 中 which / where）。
// 测试时不调：测试直接传 binDir。
// 探测目标永远是 META.binaryName（jc 自身），不是用户配置的 CLI 别名——
// launcher 的目的是把别名转发到 jc，所以必须先在 PATH 里找到 jc 自身。
export function detectJcBinDir(jcCommand: 'which' | 'where' = process.platform === 'win32' ? 'where' : 'which'): string | null {
  const r = spawnSync(jcCommand, [META.binaryName], { encoding: 'utf-8' })
  if (r.status !== 0) return null
  const first = r.stdout.split(/\r?\n/).filter(Boolean)[0]
  if (!first) return null
  // which/where 返回绝对路径；取 dirname
  const sep = first.includes('\\') ? '\\' : '/'
  const idx = first.lastIndexOf(sep)
  return idx > 0 ? first.slice(0, idx) : null
}
